apiVersion: skaffold/v2beta24
kind: Config
build:
  artifacts:
    - image: donalonzo/movie-night-client
      context: client
      docker:
        buildArgs:
          mode: watch
      sync:
        infer:
          - "public/*"
          - "src/**"
    - image: donalonzo/movie-night-server
      context: server
      docker:
        buildArgs:
          mode: watch
      sync:
        infer:
          - "src/**"
deploy:
  helm:
    releases:
      - name: movie-night
        chartPath: .k8s
        artifactOverrides:
          images.client: donalonzo/movie-night-client
          images.server: donalonzo/movie-night-server
        imageStrategy:
          helm: {}
        setValues:
          host: movie.boman.lo
          images.client.pullPolicy: Never
          images.server.pullPolicy: Never
