apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: {{ .Values.images.server.repository }}:{{ .Values.images.server.tag }}
        imagePullPolicy: {{ .Values.images.server.pullPolicy }}
        ports:
        - containerPort: 80
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-configmap
              key: database_url
        - name: AUTHENTICATION_SECRET
          valueFrom:
            secretKeyRef:
              name: authentication-secret
              key: authentication-secret
