apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  annotations:
    cert-manager.io/cluster-issuer: cluster-issuer
spec:
  entryPoints:
  - websecure
  tls:
    secretName: tls
  routes:
  - match: Host(`{{ .Values.host }}`)
    kind: Rule
    services:
    - name: frontend
      kind: Service
      port: 80
  - match: Host(`{{ .Values.host }}`) && PathPrefix(`/api`)
    kind: Rule
    services:
    - name: backend
      kind: Service
      port: 80