apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
spec:
  entryPoints:
  - websecure
  tls:
    secretName: tls
  routes:
  - match: Host(`{{ .Values.host }}`)
    kind: Rule
    services:
    - name: frontend
      port: 80
  - match: Host(`{{ .Values.host }}`) && PathPrefix(`/graphql`)
    kind: Rule
    services:
    - name: backend
      port: 80