apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}
        imagePullPolicy: {{ .Values.images.backend.pullPolicy }}
        ports:
        - containerPort: 80
        env:
        - name: MONGO_HOST
          value: {{ .Values.mongo.host }}
        - name: MONGO_PORT
          value: "{{ .Values.mongo.port }}"
        - name: MONGO_DATABASE
          value: {{ .Values.mongo.database }}
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
              optional: true
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
              optional: true