name: Deliver
on:
  push:
    branches:
      - main
    tags-ignore:
      - deploy-*
jobs:
  client:
    name: Deliver donalonzo/movie-night-client
    if: "!contains(github.event.head_commit.message, '[deploy]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ !env.ACT }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: client
          push: ${{ !env.ACT }}
          tags: donalonzo/movie-night-client,donalonzo/movie-night-client:${{ github.sha }}

  server:
    name: Deliver donalonzo/movie-night-server
    if: "!contains(github.event.head_commit.message, '[deploy]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ !env.ACT }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: server
          push: ${{ !env.ACT }}
          tags: donalonzo/movie-night-server,donalonzo/movie-night-server:${{ github.sha }}
